services:
  anvil:
    build:
      context: .
      dockerfile: docker/Dockerfile.anvil
    # image: ametelnethermind/fossil-anvil:latest
    # image: fossil-anvil:latest
    platform: linux/amd64
    networks:
      - fossil
    ports:
      - "8545:8545"
    env_file:
      - ${ENV_FILE:-.env.docker}
    environment:
      - FORK_BLOCK_NUMBER=${FORK_BLOCK_NUMBER:-}
    healthcheck:
      test: ["CMD", "cast", "block-number"]
      interval: 5s
      timeout: 5s
      retries: 5

  deploy-ethereum:
    build:
      context: .
      dockerfile: docker/Dockerfile.deploy
    # image: ametelnethermind/fossil-deploy:latest
    # image: fossil-deploy:latest
    platform: linux/amd64
    networks:
      - fossil
    env_file:
      - ${ENV_FILE:-.env.docker}
    environment:
      - HOST_UID=${UID:-1000}
      - HOST_GID=${GID:-1000}
    volumes:
      - .:/app
    depends_on:
      anvil:
        condition: service_healthy
    command: ["./scripts/deploy-ethereum.sh", "docker"]

  katana:
    build:
      context: .
      dockerfile: docker/Dockerfile.katana
    # image: ametelnethermind/fossil-katana:latest
    # image: fossil-katana:latest
    platform: linux/amd64
    networks:
      - fossil
    ports:
      - "5050:5050"
    volumes:
      - ./config:/app/config
    command:
      - "katana"
      - "--messaging"
      - "/app/config/anvil.messaging.docker.json"
      - "--dev"
      - "--dev.no-fee"
      - "--dev.no-account-validation"
      - "--http.addr"
      - "0.0.0.0"
      - "--block-time"
      - "10000"
    depends_on:
      anvil:
        condition: service_healthy
      deploy-ethereum:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "katana", "--version"]
      interval: 5s
      timeout: 5s
      retries: 5

  deploy-starknet:
    build:
      context: .
      dockerfile: docker/Dockerfile.deploy
    # image: ametelnethermind/fossil-deploy:latest
    # image: fossil-deploy:latest
    platform: linux/amd64
    networks:
      - fossil
    env_file:
      - ${ENV_FILE:-.env.docker}
    environment:
      - HOST_UID=${UID:-1000}
      - HOST_GID=${GID:-1000}
      - NO_BUILD=${NO_BUILD:-}
      - ENV_TYPE=docker
    volumes:
      - .:/app
    depends_on:
      katana:
        condition: service_healthy
    command: sh -c 'if [ -n "$NO_BUILD" ]; then ./scripts/deploy-starknet.sh --no-build docker; else ./scripts/deploy-starknet.sh docker; fi'
    healthcheck:
      test: ["CMD", "test", "-f", "/app/deployment_complete.flag"]
      interval: 10s
      timeout: 5s
      retries: 30

  # ipfs:
  #   image: ipfs/go-ipfs:latest
  #   platform: linux/amd64
  #   networks:
  #     - fossil
  #   ports:
  #     - "4001:4001" # Swarm port
  #     - "5001:5001" # API port
  #     - "8080:8080" # Gateway port
  #   volumes:
  #     - ipfs_data:/data/ipfs
  #   environment:
  #     - IPFS_PROFILE=server

networks:
  fossil:
    name: fossil-network

volumes:
  ipfs_data:
