FROM ghcr.io/foundry-rs/foundry:latest

WORKDIR /app

# Install necessary tools
RUN apk add --no-cache bash curl

# Copy deployment scripts and contracts
COPY contracts ./contracts
COPY scripts ./scripts

# Make deploy script executable
RUN chmod +x /app/scripts/deploy.sh 