services:
  build-mmr:
    image: ametelnethermind/fossil-build-mmr:latest
    container_name: fossil-build-mmr
    volumes:
      - ./:/app
    command:
      [
        "--env-file",
        "${ENV_FILE:-/app/.env.docker}",
        "${NUM_BATCHES:+--num-batches}",
        "${NUM_BATCHES:+${NUM_BATCHES}}",
        "${START_BLOCK:+--start-block}",
        "${START_BLOCK:+${START_BLOCK}}",
      ]
    environment:
      - RUST_LOG=${RUST_LOG:-info}
      - ETHEREUM_RPC_URL=http://anvil:8545
      - BONSAI_API_URL=${BONSAI_API_URL:-https://api.bonsai.xyz/}
    env_file:
      - ${ENV_FILE:-.env}
    networks:
      - fossil-network

networks:
  fossil-network:
    external: true
    name: fossil-network
