services:
  fossil-client:
    # image: ametelnethermind/fossil-client:latest
    image: fossil-client:with-files
    container_name: fossil-client
    volumes:
      - ./:/app
    environment:
      - ETHEREUM_RPC_URL=http://anvil:8545
      - ENV_FILE=${ENV_FILE:-}
      - POLLING_INTERVAL=${POLLING_INTERVAL:-60}
      - START_BLOCK=${START_BLOCK:-}
      - STARKNET_MONITORING_START=${STARKNET_MONITORING_START:-}
      - BATCH_SIZE=${BATCH_SIZE:-}
    env_file:
      - ${ENV_FILE:-.env}
#     networks:
#       - fossil-network

# networks:
#   fossil-network:
#     external: true
#     name: fossil-network
