services:
  build-mmr:
    image: ametelnethermind/fossil-client:latest
    # image: fossil-client:latest
    pull_policy: always
    container_name: fossil-client
    volumes:
      - ./:/app
    entrypoint: []
    command: >
      /bin/sh -c "
      client --env-file ${ENV_FILE:-/app/.env.docker} --start-block ${START_BLOCK:-0}
      "
    environment:
      - ETHEREUM_RPC_URL=http://anvil:8545
    env_file:
      - ${ENV_FILE:-.env}
    networks:
      - fossil-network

networks:
  fossil-network:
    external: true
    name: fossil-network
