[workspace]
members = [
    "contracts/starknet/l1_message_proxy",
    "contracts/starknet/store",
    "contracts/starknet/verifier",
]

[workspace.dependencies]
starknet = "2.11.2"
assert_macros = "2.11.2"
openzeppelin_upgrades = "1.0.0"
openzeppelin_access = "1.0.0"
snforge_std = "0.40.0"
snforge_scarb_plugin = "0.40.0"

[[target.starknet-contract]]
casm = true
casm-add-pythonic-hints = true

[workspace.tool.fmt]
sort-module-level-items = true

[tool]
fmt.workspace = true

[lib]
casm = true

[cairo]
sierra-replace-ids = false

