[package]
name = "fossil_store"
version = "0.1.0"
edition = "2023_11"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet.workspace = true
verifier = { path = "../verifier" }
openzeppelin_access.workspace = true

[dev-dependencies]
assert_macros.workspace = true
snforge_std.workspace = true

[tool]
fmt.workspace = true

[[target.starknet-contract]]
sierra = true

[scripts]
test = "snforge test"

[lib]
