[package]
name = "guest-types"
version = { workspace = true }
edition = { workspace = true }

[lib]
path = "src/lib.rs"

[dependencies]
eth-rlp-types = { workspace = true }
serde = { workspace = true }
risc0-zkvm = { version = "2.3.1", default-features = false, features = ['std'] }

[dev-dependencies]
guest-fixed-utils = { path = "../guest-fixed-utils" }
