# Builder stage
FROM rust:slim-bullseye AS builder
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y curl git ca-certificates build-essential pkg-config libssl-dev jq && rm -rf /var/lib/apt/lists/*
ENV DOJO_PATH=/root/.dojo
ENV PATH="${DOJO_PATH}/bin:${PATH}"
RUN curl -L https://install.dojoengine.org | bash && \
    mkdir -p ${DOJO_PATH}/bin && \
    . "/root/.dojo/env" && \
    dojoup
# Copy config from the host into the builder stage
COPY config /app/config

# Final runtime stage
FROM debian:trixie-slim
COPY --from=builder /root/.dojo /root/.dojo
COPY --from=builder /app/config /app/config
ENV PATH="/root/.dojo/bin:${PATH}"
EXPOSE 5050
CMD ["katana", "--messaging", "/app/config/anvil.messaging.docker.json", "--dev", "--dev.no-fee", "--dev.no-account-validation", "--http.addr", "0.0.0.0"]
