[package]
name = "ipfs-utils"
version = { workspace = true }
edition = { workspace = true }
description = "IPFS utilities for handling MMR database files"
license = "MIT"

[dependencies]
tracing = { workspace = true }
curl = { workspace = true }
tokio = { workspace = true, features = ["full"] }
serde_json = { workspace = true }
dotenv = { workspace = true }
eyre = { workspace = true }
[dev-dependencies]
tempfile = { workspace = true }
