[package]
name = "mmr-utils"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
eyre = { workspace = true }
hasher = { workspace = true }
mmr = { workspace = true }
sqlx = { workspace = true }
store = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }
