name: Cairo

on:
  # Called by main workflow
  workflow_call:
  # Allow manual trigger for testing
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Starknet Foundry
        uses: foundry-rs/setup-snfoundry@v4

      - name: Setup Scarb
        uses: software-mansion/setup-scarb@v1
        with:
          scarb-lock: contracts/starknet/Scarb.lock

      - run: scarb fmt --check
      - run: scarb build
      - run: snforge test
